#!/usr/bin/env bash

# To activate the command printer
SCRIPT_DIR=$(dirname "$0")
. "$SCRIPT_DIR/../../command-printer"
activate_command_printer -r

i=1
while [ $i -le 2 ]; do
  echo $i
  ((i++))
done
