#!/usr/bin/env bash

USERNAME=my_user
FILENAME="hello_world.txt"

# To activate the command printer
SCRIPT_DIR=$(dirname "$0")
. "$SCRIPT_DIR/../../command-printer"
activate_command_printer -r --hide SECRET_TOKEN

# Function declarations are not printed by the command printer
download_file() {
  echo "Downloading file..."
  sleep 0.9
  echo "Download complete"
}

download_file \
  --user "$USERNAME" \
  --token "$SECRET_TOKEN" \
  --filename "$FILENAME"
