#!/usr/bin/env bash

# To activate the command printer
SCRIPT_DIR=$(dirname "$0")
. "$SCRIPT_DIR/../../command-printer"
activate_command_printer -r

LS_RESULT=$(ls -a  "$PWD")
LS_RESULT=`ls -a  "$PWD"`
echo $LS_RESULT
